# Generated by Django 5.1.2 on 2024-10-31 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0010_alter_pedido_medio_pago_alter_pedido_metodo_entrega'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='cantidad',
        ),
    ]
