# Generated by Django 5.1.2 on 2024-11-02 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0011_remove_pedido_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='visto',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='metodo_entrega',
            field=models.CharField(choices=[('Retiro', 'Retiro por local'), ('Envio', 'Envio a domicilio')], default='Retiro en local', max_length=25),
        ),
    ]
