# Generated by Django 5.1.2 on 2024-10-31 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0014_producto_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='nombreplural',
            field=models.CharField(blank=True, help_text='Especifica el nombre en plural de la categoría', max_length=75),
        ),
    ]
