# Generated by Django 5.1.2 on 2024-10-31 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0015_categoria_nombreplural'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='masasxunidad',
        ),
    ]
