# Generated by Django 5.1.2 on 2024-10-31 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_rename_stock_stockgeneral_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockgeneral',
            name='cantidad',
        ),
    ]
