# Generated by Django 5.1.2 on 2024-10-31 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0009_remove_stockgeneral_cantidad'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StockGeneral',
            new_name='Estado',
        ),
    ]
