# Generated by Django 5.1.2 on 2024-10-31 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0010_rename_stockgeneral_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='estado',
            name='estado',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estado',
            name='pedidosdespachados',
            field=models.SmallIntegerField(default=5),
            preserve_default=False,
        ),
    ]
